sample_blog/config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

sample_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_blog/app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
end

sample_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sample_blog/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      # 入力フォームを再描画します。
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def confirm
    @blog = Blog.new(blog_params)
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

sample_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

sample_blog/app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == "new"
      confirm_blogs_path
    elsif action_name == "edit"
      blog_path
    end
  end
end

sample_blog/app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |f| %>
<% if @blog.errors.any? %>
<div id="error_explanation">
  <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @blog.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="blog_title">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div class="blog_content">
  <%= f.label :content %>
  <%= f.text_field :content %>
</div>
<%= f.submit %>
<% end %>

<%= link_to 'ブログ一覧画面に戻る', blogs_path %>

sample_blog/app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
<%= form.hidden_field :title %>
<%= form.hidden_field :content %>
<p>タイトル:<%= @blog.title %></p>
<p>本文:<%= @blog.content %></p>
<%= form.submit  "登録する" %>
<% end %>
<%= link_to '戻る', :back %>

sample_blog/app/views/blogs/edit.html.erb
  <h2>ブログを編集する</h2>
  <%= render 'form' %>

sample_blog/app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
  <% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <td><%= link_to '編集する', edit_blog_path(blog.id) %></td>
    <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
  <% end %>
</table>

<%= link_to '新しくブログを投稿する', new_blog_path %>

sample_blog/app/views/blogs/new.html.erb
  <h2>ブログを作成する</h2>
  <%= render 'form' %>

sample_blog/app/views/blogs/show.html.erb
<h1> ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title%></p>
<p>内容: <%= @blog.content%></p>

<%= link_to 'ブログ一覧画面に戻る', blogs_path %>

sample_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>